### ISSUE TITLE
Default tags cannot be set at runtime

### ISSUE THREAD

**Issue by 1player** [IanLuites/data_daemon#2]
Though undocumented, it's possible to set some default tags by calling `use DataDaemon, tags: [foo: "bar"]`, but they are set at compile time, and it's currently impossible to have a different set of default tags at runtime — for example, tags derived from environment variables.

**Comment by IanLuites** [comment]
I think it should be possible to set `{:system, "ENV_VAR_NAME"}` for a runtime lookup env var.

Or does this not work?

**Comment by IanLuites** [comment]
(please re-open if it doesn't, because I might not have published that)
