### ISSUE TITLE
Run time configuration

### ISSUE THREAD

**Issue by 1player** [IanLuites/data_daemon#3]
While the `use DataDaemon` macro is very handy, it limits any time of run-time configurability, see also #2

My suggestion is being able to configure DataDaemon when it is included in the parent app supervisor tree, example:

```
# In your application code
defmodule Sample.DataDog do
  @moduledoc ~S"My DataDog reporter."
  use DataDaemon,
    otp_app: :my_app,
    extensions: [:datadog]
end

# In parent app supervisor
Sample.DataDog.start_link(url: "statsd+udp://localhost:8125")
```

Any parameter passed to `start_link` overrides any set in the application config file.

I'd like to take a stab at this, but as it'll break the existing API I'll wait for your go-ahead.

**Comment by IanLuites** [comment]
Missed these notes for a while, decided to pick it up together with a bit of the DNS rework.

**Comment by IanLuites** [comment]
This was added in #5 and now improved in #6!
